feat: footer new design
gita/gita-frontend-v2 pull request #12
Opened 2021-12-03 13:48 UTC by akshitarora921

part of #11

2021-12-03 15:14 UTC, ayushsoni1010 approved these changes

2021-12-05 18:04 UTC, Gupta-Anubhav12 approved these changes

2021-12-05 18:08 UTC, Gupta-Anubhav12 requested changes
Footer in this is fixed and header is not

2021-12-06 06:43 UTC, akshitarora921 commented
@Gupta-Anubhav12 I will merge the main branch and then we can merge it

2021-12-06 06:57 UTC, Gupta-Anubhav12 commented
> h and I will merge

sure

2021-12-06 07:29 UTC, merged