Fixed the syntax error in footer
gita/gita-frontend-v2 pull request #150
Opened 2023-06-29 16:34 UTC by eht-ck

fixed: syntax error in the footer and open in new tab functionality to the about-us,blog,donate,press,api and contact-us

Description: Getting  syntax error when setting up repo
`
Caused by:
    0: failed to process input file
    1: Syntax Error
wait  - compiling /_error (client and server)...
error - ./components/Footers/Footer.js
Error:
  x Expected ',', got '{'
    ,----
 12 | {
    : ^
    `----
`
Fixed the syntax and added opening the footer links in new tab

2023-07-01 18:34 UTC, samanyougarg commented
Thank you for the PR @eht-ck!

2023-07-01 18:34 UTC, samanyougarg commented
- [ ] These buttons should be properly aligned and of the same height and width.

<img width="420" alt="Screenshot 2023-07-02 at 12 03 57 AM" src="https://github.com/gita/bg-frontend/assets/32533774/15d1094a-9bad-488d-9bc4-34c6b798c6c0">

2023-07-01 18:35 UTC, samanyougarg commented
- [ ] Make the ved Vyas link in orange color same as our theme. Also, this link should open in a new tab.

<img width="559" alt="Screenshot 2023-07-02 at 12 04 45 AM" src="https://github.com/gita/bg-frontend/assets/32533774/cb49dc3b-f25a-4811-b594-f97397a444f5">

2023-07-01 18:35 UTC, samanyougarg commented
- [ ] Remove the Instagram link as we don't have an official account.

2023-07-01 18:37 UTC, samanyougarg requested changes

2023-07-01 18:37 UTC, samanyougarg commented on components/Footers/Footer.js
> +    { name: "About Us", href: " /about ", target: "_blank" },
This should open in the same tab since it is an internal link.

2023-07-01 18:37 UTC, samanyougarg commented on components/Footers/Footer.js
> +    { name: "Press", href: "", target: "_blank" },
Hide this for now since we dont have a Press link.

2023-07-01 18:37 UTC, samanyougarg commented on components/Footers/Footer.js
> +      name: "Contact Us",
This is an email link should open in the same tab.

2023-07-02 09:03 UTC, eht-ck commented
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/97c37977-ae9c-45a8-ab73-e6fd41a267ad)

![image](https://github.com/gita/gita-frontend-v2/assets/95522110/73f15aaf-8982-41ea-96e5-1b34c22845fd)
both images are now of 114.33*39.99 aspect ratio

2023-07-07 19:06 UTC, samanyougarg commented
- [ ] Too much gap between the buttons.

<img width="496" alt="Screenshot 2023-07-08 at 12 36 14 AM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/d628d220-fa03-4b43-8429-ba96f8aebd1b">

2023-07-07 19:10 UTC, samanyougarg commented
- [ ] Let's use SVGs. There are of the same size.

![app-store](https://github.com/gita/gita-frontend-v2/assets/32533774/f11f1a78-15aa-45c7-b87d-4d62cf6b7afe)
![google-play](https://github.com/gita/gita-frontend-v2/assets/32533774/471dec92-6f65-454a-8092-4215f5e992c7)

2023-07-07 19:11 UTC, samanyougarg commented
- [ ] Also, please see the AI reviewer comments above. @eht-ck

2023-07-08 03:05 UTC, eht-ck commented
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/3ef9b8f8-c133-44ca-8b33-f5cfde81a772)
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/fe6363e8-0b46-479f-ba58-4648c123be08)
Fixed the size and spacing between app  imgs

2023-07-08 03:28 UTC, eht-ck commented
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/3ef9b8f8-c133-44ca-8b33-f5cfde81a772)
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/fe6363e8-0b46-479f-ba58-4648c123be08)
Fixed the size and spacing between app  images and tried to resolve relevant suggestion of AI reviewer

2023-07-08 07:06 UTC, samanyougarg commented
@eht-ck Distance between the buttons keeps increasing on higher resolutions. Try increasing the display zoom to 125% and then test.

<img width="408" alt="Screenshot 2023-07-08 at 12 35 59 PM" src="https://github.com/gita/gita-frontend-v2/assets/32533774/0cbdc681-a998-4029-b87a-02923c86865c">

2023-07-08 07:31 UTC, eht-ck commented
> @eht-ck Distance between the buttons keeps increasing on higher resolutions. Try increasing the display zoom to 125% and then test.
> 
> <img alt="Screenshot 2023-07-08 at 12 35 59 PM" width="408" src="https://user-images.githubusercontent.com/32533774/251946688-0cbdc681-a998-4029-b87a-02923c86865c.png">
It is correct on my system
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/061e18e9-6f0c-4aaf-a531-fe84e6e95c40)
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/c6155bc7-03d3-4ee9-b259-bbd2fdcf8541)

2023-07-08 14:25 UTC, samanyougarg commented
Sorry, I meant if you zoom out. On bigger screens, it is like this.

2023-07-08 14:26 UTC, samanyougarg commented
Also, please clean up the PR to remove the other image files that are not needed anymore.

2023-07-08 15:41 UTC, eht-ck commented
@samanyougarg Fixed the image gap issue  for high resolution screen and removed other images  files from public directory which arent being used.
![image](https://github.com/gita/gita-frontend-v2/assets/95522110/cf69e94e-74c9-400e-bccc-14482f8dbd56)

2023-07-08 16:02 UTC, samanyougarg commented
Looks good, thank you!

2023-07-08 16:02 UTC, samanyougarg approved these changes

2023-07-08 16:03 UTC, merged