fix: Add outlines reverting PR
gita/gita-frontend-v2 pull request #19
Opened 2021-12-08 07:19 UTC by akshatj2209

There was a PR that needed to be fixed due to it having a negative impact on the accessibility of the website. I tried to revert the changes and hope that the issue is fixed. Please review and merge

2021-12-08 14:57 UTC, Gupta-Anubhav12 commented on components/Headers/IndexHeader.js
>                          "group bg-white rounded-md inline-flex items-center text-base font-medium hover:text-gray-500 focus:outline-none "
Hey @akshatj2209 you missed this, please remove outline none from here too

2021-12-08 14:58 UTC, Gupta-Anubhav12 requested changes
please remove outline from chapter link too

2021-12-08 15:01 UTC, Gupta-Anubhav12 commented
Hey @akshatj2209 
Thanks for this contribution, the audioplayer is missing a audio length seeker as in original designs, please fix that too before we merge

2021-12-13 08:37 UTC, akshatj2209 commented
The Progress Bar has been added @Gupta-Anubhav12 , Please review it and specify any other requirements.

2021-12-13 17:10 UTC, Gupta-Anubhav12 commented
Hey it works smooth, great 
merging now

2021-12-13 17:10 UTC, Gupta-Anubhav12 approved these changes

2021-12-13 17:12 UTC, Gupta-Anubhav12 commented
There are some imperfections but we can merge it for MVP and look at those afterwards ,
Thanks for contributing @akshatj2209

2021-12-13 17:12 UTC, merged