added custom 404 page [fixes #210]
gita/gita-frontend-v2 pull request #226
Opened 2023-10-06 17:53 UTC by sarthak-kumar-shailendra

Have modified the custom 404 page.

Previous UI
<img width="1114" alt="Screenshot 2023-10-06 at 11 03 40 PM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/33f64a6e-5d20-4ed8-adf6-067450fe8918">

<img width="1105" alt="Screenshot 2023-10-06 at 11 03 31 PM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/bada5d1b-b895-4152-b312-4d35d818b4db">

New UI 

<img width="1175" alt="Screenshot 2023-10-06 at 11 03 00 PM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/7dfbc37f-2efb-4d65-b4de-8006c9ee391f">
<img width="1186" alt="Screenshot 2023-10-06 at 11 03 21 PM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/d80a277f-08d3-4015-a1ff-e52742b5a6f5">

Have added translation for hindi as well

<img width="1159" alt="Screenshot 2023-10-06 at 11 21 48 PM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/ace7c400-c072-4c16-80e2-c146ccdc602c">

This UI renders when wrong chapter or verse is entered in URL and also in case the verse of the day is missing

2023-11-21 13:02 UTC, sarthak-kumar-shailendra commented
@samanyougarg

2023-12-28 15:45 UTC, sarthak-kumar-shailendra commented
Hare Krishna
pls review @samanyougarg

2024-01-20 18:13 UTC, samanyougarg commented
Tried with `/radheradhe` but I don't get a 404 page:
![CleanShot 2024-01-20 at 23 42 51@2x](https://github.com/gita/gita-frontend-v2/assets/32533774/afb4cfc3-ad49-4bc8-8165-de0cb4808d55)

2024-01-20 18:14 UTC, samanyougarg commented
Works for /chapters but there is too much padding below the image and above the footer. Additionally, the header should be visible on this page.

![CleanShot 2024-01-20 at 23 44 08@2x](https://github.com/gita/gita-frontend-v2/assets/32533774/6f79fab3-a218-4600-8570-b7d460eb1bfe)

2024-01-20 18:15 UTC, samanyougarg requested changes
Please see comments.

2025-10-03 13:38 UTC, sarthak-kumar-shailendra commented
Suggestions have been addressed in https://github.com/gita/gita-frontend-v2/pull/262. Hence closing this one.

2025-10-03 13:38 UTC, closed without merging