quotes mobile css fix [fixes #216]
gita/gita-frontend-v2 pull request #228
Opened 2023-10-08 18:37 UTC by sarthak-kumar-shailendra

[Fixes #216] 
This PR resolves quotes mobile css overflow issue.

The issue was because of fixed height mentioned h-96 in quotes page file. So I have changed it to min-h-screen.
(Here I have assumed we cannot change the font size)

<img width="314" alt="Screenshot 2023-10-08 at 11 56 19 PM" src="https://github.com/gita/gita-frontend-v2/assets/69191344/41954df1-88cb-4a8d-90b9-1a62cebb6401">

Pls check the UI in different devices and suggest any changes if required

2023-12-28 15:45 UTC, sarthak-kumar-shailendra commented
Hare Krishna
pls review @samanyougarg

2024-01-20 18:11 UTC, samanyougarg commented
This is adding a lot of unneeded whitespace on the top and bottom of the quotes. Please fix it:
![CleanShot 2024-01-20 at 23 41 11@2x](https://github.com/gita/gita-frontend-v2/assets/32533774/3e200d21-4bf9-428c-8737-7ca61e87bfb8)

2024-01-20 18:12 UTC, samanyougarg requested changes
Whitespace needs fixing.

2024-01-21 20:28 UTC, sarthak-kumar-shailendra commented
@samanyougarg pls check now

2024-04-25 16:49 UTC, closed without merging